### ISSUE TITLE
GetReceipt endpoint throws exception.

### ISSUE THREAD

**Issue by RiaanVR** [Evidos/SignhostClientLibrary#19]
Hi, 
I have entered proper testing of an application that makes use of your library to integrate with Ondertekenen.nl.
I am receiving a very obscure exception with no additional information or stack trace.

Message: receipt not found.
Source: Flurl.Http
ExceptionType: NotFoundException

I am using the same transaction Id I received when starting the sign request.

Testing with Postman does download the receipt do you have any insight? 

Is the Flurl library dependable? I might need to rewrite your library locally if I continue to receive strange results.

**Comment by MrJoe** [comment]
The message `receipt not found` is the error the ondertekenen.nl API is returning. Which could mean the transaction id is not valid or the transaction is not yet ready, although that should also give you a 404 in postman. 

We have a pull request which is bumping the library to .net standard and also removes the flurl library as a dependency.

**Comment by RiaanVR** [comment]
Yes, that is the response, but could you think it is due to me attempting to download the receipt before it has been generated? 

I have an asp.net handler which takes care of the post back, in that handler I download the signed document and receipt once all parties have signed it. From you knowledge is there a period of time I should wait?

**Comment by MrJoe** [comment]
As soon as the status is 30 the receipt should be available. Could it be you are downloading the receipt when you received a postback for status 20?

Be careful with executing lots of business logic within your postback handler, because signhost won't execute the next postback until the current was succesfull (http status 200) and will queue any pending postbacks when necessary .

**Comment by RiaanVR** [comment]
Thanks for the information, I believe my check to download the receipt was a bit preemptive, I was not explictly waiting for status 30.
