### ISSUE TITLE
Files property is always null in PostbackTransaction, missing property ModifiedDateTime

### ISSUE THREAD

**Issue by berendengelbrecht** [Evidos/SignhostClientLibrary#50]
When deserializing an Evidos Postback event in PostbackTransaction, I experience two issues:

1. The Files property is always null after deserialization. 
This is because PostbackTransaction is derived from Transaction, that has a _private_ set on the property.
The Files collection is required to allow the client to enumerate signed files from the postback data.

2. PostbackTransaction and Signer lack the ModifiedDateTime property, that is returned in the json data
The property is useful to filter for new changes in a PostbackTransaction, e.g., signers with new "sign" activities can be queried like this:
`return SignHostTransaction.Signers
        .Where(s => s.Activities.Any(a => a.Code == ActivityType.Signed
          && (a.CreatedDateTime >= SignHostTransaction.ModifiedDateTime)))
        .ToList();`

**Comment by MrJoe** [comment]
The ModifiedDateTime is unreliable and is one of the reasons it is not provided in the postback data. 
As you can see it isn't mentioned as a documented property at https://evidos.github.io/endpoints/##/definitions/Transaction , we should probably drop it from the sample responses as well. 
The only reason we return this on a GET is for compatability reasons, but again it is unreliable to use.

We should fix the Files property though.

**Comment by berendengelbrecht** [comment]
Too bad that I shouldn't use ModifiedDateTime. Not using it makes it more difficult to identify the intent of a callback event and potentially leads to repeated processing at our end (so be it ...).

However, please note that the main part of my bug report was issue 1: The Files property is always null after deserialization.
