### ISSUE TITLE
API Transactions Failing Due to Lack of Support for `null` Values in API calls

### ISSUE THREAD

**Issue by JoostVanVelthoven** [Evidos/SignhostClientLibrary#66]
As of the recent API update on October 20th, 2023, the API has stopped accepting `null` values in metadata calls. This change was unintended and broke transaction creation for our implementation as well. The issue has been acknowledged by the API maintainers as per their status update:

> "An unintended consequence of this release is that we also did not accept null values anymore in the API and throw an error. This was not clear initially as a consequence, and because adding null values in JSON is bad development practice and also warned against explicitly in our API documentation, we did not broadly test this scenario."  
> \- [API Status Update, Oct 23, 2023](https://evidos.github.io/endpoints/)

This has impacted our transaction creation and resulted in the status 'Waiting for document'.

#### Expected Behavior

The client should automatically remove fields that are set to null, instead of placing null values or causing transaction failures. 

#### Current Behavior

Transaction creation fails when `null` values are passed in the body payload of the API call.

#### Steps to Reproduce

1. Create a new transaction via the API.
2. Include `null` values in the metadata.
3. Transaction creation fails with status 'Waiting for document'.

#### Suggested Fix

On the consumer end, add the following JSON serializer settings to ignore `null` values:

```csharp
new JsonSerializerSettings
{
    NullValueHandling = NullValueHandling.Ignore
}
```

In the `JsonContent<T>` class, update the `ToJson` function as follows:

```csharp
private static string ToJson(T value)
{
    return JsonConvert.SerializeObject(value, new JsonSerializerSettings
    {
        NullValueHandling = NullValueHandling.Ignore
    });
}
```

**Comment by PaulLoth** [comment]
On the API end Signhost has performed a fix to accept null values for the time being. We are reaching out to change the .Net client library as well.
